// Content for the site — kept as a global window.SITE so other files can reach it.

window.SITE_NAME = "Ius Quanticum";

window.SITE = {
  posts: [
    {
      slug: "ia-classica-a-revolucio-quantica-sector-legal",
      date: "2026-05-16",
      readMin: 14,
      title: "De la IA clàssica a la Revolució Quàntica: Què necessita saber el sector legal?",
      dek: "L'advocacia d'empresa i els equips in-house ja conviuen amb la IA clàssica, però la Segona Revolució Quàntica obre un escenari de ruptura que exigeix alfabetització estratègica immediata.",
      tags: ["ia quàntica", "computació clàssica", "jurisprudència"],
      body: [
        { type: "p", text: "L'advocacia dels negocis i les assessories jurídiques d'empresa (in-house) ja han començat a interioritzar l'impacte de la Intel·ligència Artificial (IA) en el seu dia a dia. Tanmateix, a l'horitzó s'està gestant un canvi tecnològic d'una magnitud superior que no representa una simple millora o acceleració dels sistemes actuals, sinó una ruptura fonamental en la manera com processem la informació: la Segona Revolució Quàntica." },
        { type: "p", text: "Per als partners i directors legals, comprendre les bases d'aquesta tecnologia no és un exercici de ciència-ficció, sinó una necessitat estratègica per anticipar riscos i liderar el compliment normatiu del futur. A continuació, es desgranen els conceptes clau que tot jurista de perfil directiu ha de conèixer." },
        { type: "h2", text: "1. El salt de la lògica binària: De Bits a Qubits" },
        { type: "p", text: "La informàtica clàssica es basa en bits, unitats d'informació que només poden estar en un de dos estats: 0 o 1. Aquesta arquitectura reflecteix la lògica binària que sovint utilitzem en el raonament jurídic: una prova és admissible o inadmissible, un acusat és culpable o innocent, una clàusula és vàlida o nul·la." },
        { type: "p", text: "La computació quàntica, per contra, utilitza partícules subatòmiques (com fotons o electrons) per crear qubits (bits quàntics). A causa de les lleis de la mecànica quàntica, un qubit no està limitat a ser un 0 o un 1 de manera excloent, sinó que pot albergar els dos valors alhora. Això suposa una explosió en la capacitat de càlcul que la informàtica tradicional no podrà igualar mai." },
        { type: "h2", text: "2. La Superposició Quàntica: Avaluant totes les rutes alhora" },
        { type: "p", text: "La propietat física que permet als qubits existir en múltiples estats simultàniament s'anomena superposició. Amb un to pedagògic, imaginem que hem de trobar una agulla en un paller o buscar un argument específic en una biblioteca jurídica infinita. Un ordinador clàssic, per molt ràpid que sigui, haurà de buscar llibre per llibre i prestatge per prestatge de manera seqüencial. En canvi, un ordinador quàntic, gràcies a la superposició, pot explorar tots els llibres i tots els prestatges simultàniament." },
        { type: "p", text: "Traduït a l'àmbit jurídic d'alt nivell, aquesta propietat permetrà avaluar de manera concurrent i no pas seqüencial totes les interpretacions legals possibles d'una norma, o totes les rutes de resolució en un litigi complex, considerant milers de variables al mateix temps." },
        { type: "h2", text: "3. Quantum Machine Learning (QML): La nova frontera de la Justícia Predictiva" },
        { type: "p", text: "Què passa quan unim la immensa capacitat de processament paral·lel de la quàntica amb l'aprenentatge automàtic de la IA? Neix el Quantum Machine Learning (QML). Mentre que la IA clàssica que utilitzem avui detecta patrons en grans bases de dades amb certes limitacions d'escalabilitat i temps d'entrenament, el QML pot capturar correlacions subtils en dades multidimensionals a una velocitat exponencialment superior." },
        { type: "list", items: ["Justícia predictiva d'alta precisió: els models de QML podran analitzar no només milions de textos legals, sinó també variables econòmiques, sociodemogràfiques i de mercat per anticipar el resultat d'un litigi i facilitar acords extrajudicials primerencs basats en probabilitats matemàtiques gairebé exactes.", "Investigacions complexes (e-Discovery): la capacitat per processar conjunts de dades no estructurades a velocitats extremes permetrà detectar patrons de blanqueig de capitals, fraus corporatius o manipular xarxes de documents en qüestió de minuts en comptes de mesos."] },
        { type: "h2", text: "Conclusió: L'imperatiu de l'alfabetització quàntica" },
        { type: "p", text: "Com a líders legals, la qüestió ja no és si aquesta tecnologia arribarà, sinó com cal preparar les organitzacions per al seu impacte. Les capacitats d'aquests sistemes alteraran les dinàmiques dels contractes tecnològics, obriran debats sobre l'opacitat de les decisions algorítmiques judicials i, el que és més urgent, posaran en escac la criptografia actual que protegeix el secret professional i les dades dels clients." },
        { type: "quote", text: "Desenvolupar alfabetització quàntica no implica convertir-se en físic, sinó entendre la nova lògica del risc per anticipar defenses legals, reforçar diligència deguda en ciberseguretat i preparar la propera onada reguladora europea." },
      ],
    },
    {
      slug: "ia-als-tribunals-avui-justicia-predictiva",
      date: "2026-05-08",
      readMin: 16,
      title: "La IA als Tribunals avui: De l'automatització de tasques a la justícia predictiva",
      dek: "Anàlisi pedagògica de l'estat actual de la IA judicial: de l'automatització processal als sistemes de valoració de riscos, amb focus en COMPAS, VIOGÉN i garanties de procés degut.",
      tags: ["justícia predictiva", "ia als tribunals", "compas"],
      body: [
        { type: "p", text: "L'administració de justícia i la pràctica legal es troben al llindar d'una metamorfosi històrica. Per a jutges, reguladors i advocats d'empresa (in-house), la intel·ligència artificial (IA) ha deixat de ser una promesa futurista per convertir-se en una eina present i amb impactes reals." },
        { type: "p", text: "No obstant això, cal desmitificar i estructurar com s'està aplicant aquesta tecnologia als tribunals actualment: des de la simple automatització de processos mecànics fins a la complexa i controvertida justícia predictiva i d'avaluació de riscos." },
        { type: "h2", text: "1. El punt de partida: L'automatització processal" },
        { type: "p", text: "Abans de parlar de jutges-robot, la primera fase de la integració de la IA als tribunals se centra en l'eficiència de la gestió. Actualment, sistemes basats en Processament del Llenguatge Natural i models com els arbres de decisió s'utilitzen per extreure dades de grans volums documentals (e-discovery), anonimitzar sentències i classificar o prioritzar assumptes per matèria o urgència." },
        { type: "p", text: "Aquestes aplicacions, concebudes com a eines d'assistència, no plantegen de partida els dilemes més intensos de drets fonamentals i aporten beneficis tangibles: descol·lapsar agendes, reduir temps de tramitació i augmentar la qualitat del servei públic." },
        { type: "h2", text: "2. El salt a l'avaluació de riscos: Els casos COMPAS i VIOGÉN" },
        { type: "p", text: "La controvèrsia apareix quan la IA deixa les tasques mecàniques i entra en l'esfera de la predicció de la conducta humana, especialment en l'àmbit penal. La justícia predictiva utilitza dada històrica i estadística per calcular probabilitats futures, com el risc de reincidència o de fugida." },
        { type: "list", items: ["COMPAS (EUA): instrument algorítmic per valorar risc de reincidència amb impacte en mesures cautelars i penes. El cas Eric Loomis va visibilitzar el conflicte entre secret comercial del software i dret de defensa, així com problemes de biaix algorítmic detectats en auditories.", "VIOGÉN (Espanya): sistema de naturalesa actuarial per valorar risc en violència de gènere i assignar nivells d'alerta. Tot i la seva utilitat operativa, exigeix actualització en transparència, explicabilitat i control judicial efectiu per evitar automatismes cecs."] },
        { type: "h2", text: "3. El debat ètic i processal: La caixa negra i el dret a la motivació" },
        { type: "p", text: "La lliçó de COMPAS obre un debat central: si la màquina opera com una caixa negra on no es pot reconstruir el camí lògic de la conclusió, com es protegeixen les garanties del procés degut? La pregunta no és tecnològica, és constitucional i processal." },
        { type: "list", items: ["Obligació de motivar: les resolucions judicials han d'expressar raons i justificació interpretativa; delegar en un score opac debilita aquesta exigència.", "Presumpció d'innocència: un model ex ante basat en predicció pot desplaçar la càrrega de defensa cap al que una màquina estima que passarà.", "Il·lusió d'objectivitat: si les dades històriques incorporen desigualtats estructurals, l'algoritme tendeix a reproduir i amplificar aquestes distorsions."] },
        { type: "h2", text: "Conclusió: Cap a una regulació centrada en l'ésser humà" },
        { type: "p", text: "El Reglament Europeu d'Intel·ligència Artificial (AI Act) marca un criteri rellevant en considerar d'alt risc els sistemes d'IA utilitzats en administració de justícia per avaluar proves o riscos personals. Aquest marc exigeix transparència, registre d'activitat i auditories periòdiques." },
        { type: "quote", text: "L'algoritme no dicta el futur: només ofereix una advertència estadística. L'automatització pot agilitzar el sistema, però les decisions sobre drets, patrimoni o llibertat exigeixen empatia, context, equitat i raonament ètic humà." },
      ],
    },
    {
      slug: "fi-instruccions-interminables-ediscovery-quantica",
      date: "2026-04-27",
      readMin: 13,
      title: "La fi de les instruccions interminables: L'e-Discovery impulsat per la quàntica",
      dek: "Tutorial pràctic per entendre com l'algorisme de Grover pot accelerar l'exploració de bases de dades desestructurades en litigis i investigacions internes.",
      tags: ["e-discovery", "algorisme grover", "búsqueda quàntica"],
      body: [
        { type: "p", text: "L'e-discovery clàssic pateix quan la informació és massiva, heterogènia i poc estructurada. El cost no és només computacional: també és processal, perquè cada iteració de recerca i depuració allarga terminis i incrementa risc de disputa probatòria." },
        { type: "h2", text: "Què aporta Grover" },
        { type: "p", text: "L'algorisme de Grover és una tècnica de cerca quàntica per reduir el nombre de consultes necessàries en determinats tipus de problemes no estructurats. No resol tot l'e-discovery, però pot reduir la càrrega en fases específiques de localització i filtrat inicial." },
        { type: "h2", text: "Guia de decisió per equips legals" },
        { type: "list", items: ["Identifica quina part del flux de recerca és realment no estructurada.", "Separa fase de triatge tècnic i fase de validació jurídica humana.", "Defineix una política de traçabilitat: query, transformacions i criteri de rellevància." ] },
        { type: "p", text: "Per a in-house counsel i partners, la clau és pragmàtica: començar per pilots acotats, amb mètriques de temps, costos i qualitat probatòria comparables amb el mètode clàssic." },
        { type: "quote", text: "En e-discovery, velocitat sense auditabilitat és només risc més ràpid." },
        { type: "p", text: "Aquest article és tutorial: prioritza com implementar decisions i com evitar que la promesa tècnica col·lapsi en discussió processal." },
      ],
    },
    {
      slug: "descollapsar-jutjats-qaoa-gestio-agendes",
      date: "2026-04-11",
      readMin: 10,
      title: "Descol·lapsar els jutjats: L'Algorisme QAOA i la gestió d'agendes judicials",
      dek: "Com QAOA pot abordar el problema combinatori de coordinar jutges, sales, advocats i finestres processals en calendaris judicials de màxima pressió.",
      tags: ["qaoa", "optimització quàntica", "calendari judicial"],
      body: [
        { type: "p", text: "La gestió d'agendes judicials és un problema d'optimització amb restriccions múltiples: disponibilitat de jutges, sales, advocats, terminis legals, preferències de procediment i incidències sobrevingudes. Quan aquest volum creix, els sistemes clàssics tendeixen a degradar-se ràpidament." },
        { type: "h2", text: "Per què QAOA és rellevant" },
        { type: "p", text: "QAOA (Quantum Approximate Optimization Algorithm) és una aproximació pensada per problemes combinatoris complexos. En calendari judicial no promet perfecció, però sí la possibilitat de trobar solucions de millor qualitat dins de finestres temporals útils per a operació real." },
        { type: "h2", text: "On és l'oportunitat institucional" },
        { type: "list", items: ["Reducció de conflictes d'agenda de darrera hora.", "Millor ús de sales i recursos administratius.", "Menys ajornaments evitables i més previsibilitat processal." ] },
        { type: "p", text: "Per a managers de jutjats i CIOs, l'estratègia recomanable és començar amb simulació híbrida: modelar restriccions reals, comparar contra heurístiques actuals i desplegar progressivament per jurisdicció o tipus d'assumpte." },
        { type: "quote", text: "El valor d'un calendari judicial no és només omplir franges, sinó reduir friccions processals sense perdre garanties." },
        { type: "p", text: "Aquest article és d'oportunitat: proposa un full de ruta per a modernització operativa sense confondre innovació amb experimentació descontrolada." },
      ],
    },
  ],

  projects: [
    {
      slug: "trobar-article",
      name: "Trobar un Article",
      tagline: "Cerca per número d'article, títol o text legal i accedeix directament a la disposició rellevant.",
      status: "live",
      year: "2026",
      stack: "Motor de cerca jurídica · Índex d'articles · Navegació per codis",
      kind: "eina",
      url: "https://quediulallei.cat/",
      summary: "Mòdul central de lectura estructurada per trobar ràpidament articles dins dels codis jurídics disponibles.",
      angle: "Prioritza accés clar i directe, sense obligar la persona usuària a dominar sigles o arquitectura normativa prèvia.",
      output: "Resultats per article, coincidència textual i accés immediat a la norma completa.",
      questions: [
        "Com prioritzar resultats sense perdre precisió jurídica?",
        "Quin pes donar al text literal davant del context normatiu?",
        "Com mostrar relacions entre articles sense sobrecarregar la lectura?"
      ],
    },
    {
      slug: "orientacio-tematica",
      name: "Orienta't per Temàtica",
      tagline: "Quan tens el problema però no saps quina norma consultar, et proposa codis i articles inicials.",
      status: "beta",
      year: "2026",
      stack: "Taxonomia jurídica · Recomanador per matèries · Flux guiat",
      kind: "orientació",
      url: "https://quediulallei.cat/",
      summary: "Passarel·la de descoberta per començar des del dubte i arribar a la norma adequada en menys passos.",
      angle: "Pensa en problemes reals (filiació, successions, garanties, societats) i no en classificacions acadèmiques abstractes.",
      output: "Rutes temàtiques, recomanacions d'articles i enllaços als codis rellevants.",
      questions: [
        "Com evitar recomanacions massa genèriques?",
        "Com distingir orientació pedagògica d'assessorament jurídic?",
        "Com mantenir cobertura equilibrada entre àmbits materials?"
      ],
    },
    {
      slug: "hermes-comprensio",
      name: "Hermes",
      tagline: "Espai d'exploració guiada per comprendre millor una norma amb resum, context i exemples.",
      status: "live",
      year: "2026",
      stack: "IA assistida · Prompting legal · Revisió humana",
      kind: "assistència",
      url: "https://quediulallei.cat/",
      summary: "Mòdul d'interpretació assistida pensat per augmentar l'autonomia en la lectura jurídica, no per substituir professionals.",
      angle: "Manté un enfocament pedagògic: explica, contextualitza i adverteix límits abans de suggerir conclusions.",
      output: "Resums orientatius, exemples d'aplicació i preguntes de verificació.",
      questions: [
        "Com garantir que el llenguatge sigui clar sense simplificar en excés?",
        "Com mostrar incertesa interpretativa de manera transparent?",
        "Com reforçar el disclaimer de no-consultori en cada interacció?"
      ],
    },
    {
      slug: "jurisprudencia-doctrina",
      name: "Jurisprudència i Doctrina",
      tagline: "Connexió entre articles normatius, sentències i publicacions acadèmiques relacionades.",
      status: "concept",
      year: "2026",
      stack: "Indexació documental · Enllaçat semàntic · Curadoria",
      kind: "repositori",
      url: "https://quediulallei.cat/codi-consum",
      summary: "Capa complementària per contrastar text legal amb pràctica jurisprudencial i debat doctrinal.",
      angle: "Especialment útil quan una disposició requereix context aplicatiu per ser realment entesa.",
      output: "Fitxes d'articles amb sentències vinculades i referències acadèmiques.",
      questions: [
        "Quin criteri d'inclusió de sentències evita biaixos?",
        "Com es presenta doctrina contradictòria sense confondre l'usuari?",
        "Com actualitzar enllaços i cites sense degradar confiança?"
      ],
    },
    {
      slug: "dretvisual-clars",
      name: "DretVisual & Clar",
      tagline: "Biblioteca visual d'apunts, esquemes i vídeos per estudiar dret espanyol i català amb alta densitat i navegació per branques.",
      status: "live",
      year: "2026",
      stack: "Vídeos · Visuals interactius · Mòduls docents",
      kind: "biblioteca",
      url: "https://dretvisual.quediulallei.cat/",
      summary: "Projecte d'aprenentatge jurídic visual amb itineraris per penal, civil, administratiu, constitucional, processal, financer i mercantil.",
      angle: "Combina formats audiovisuals i esquemes perquè la persona usuària pugui memoritzar i entendre estructura normativa en menys temps.",
      output: "Graella de matèries, accés a vídeos, visuals i mòduls especialitzats.",
      questions: [
        "Com mantenir rigor doctrinal en formats ultra-breus?",
        "Com harmonitzar actualització normativa amb contingut audiovisual?",
        "Com enllaçar estudi memorístic amb comprensió aplicativa?"
      ],
    },
    {
      slug: "viajusta",
      name: "ViaJusta",
      tagline: "Explica el teu problema i obtén un camí processal general per orientar els primers passos.",
      status: "live",
      year: "2026",
      stack: "Orientació processal · Flux de casos · Disclaimer legal",
      kind: "orientador",
      url: "https://viajusta.vercel.app/",
      summary: "Eina d'orientació inicial per casos freqüents com acomiadaments, fiances, multes, comissions abusives o accidents.",
      angle: "Posa el focus en seqüència d'actuació i no en resposta jurídica tancada, mantenint el límit de no-consultori.",
      output: "Camí processal orientatiu i enllaços a recursos complementaris.",
      questions: [
        "Com evitar que una ruta orientativa es llegeixi com consell definitiu?",
        "Com ajustar rutes a diferències territorials i competencials?",
        "Com recollir casos límit sense saturar la interfície?"
      ],
    },
    {
      slug: "feed-juridic",
      name: "Feed Jurídic",
      tagline: "Portada editorial connectada a novetats jurídiques amb context, radar i accés directe a fonts originals.",
      status: "live",
      year: "2026",
      stack: "Feed de novetats · Radar sectorial · Digest",
      kind: "monitor",
      url: "https://feedjuridic.vercel.app/index.html",
      summary: "Canal de seguiment diari amb senyals del dia, resum executiu, focus sectorial i traçabilitat de font.",
      angle: "No es limita a titulars: contextualitza moviments i permet filtrar per categories i canals.",
      output: "Dashboard de novetats, digest i radar recent amb enllaços de verificació.",
      questions: [
        "Com garantir qualitat de context quan el volum de novetats augmenta?",
        "Quina jerarquia editorial minimitza soroll i maximitza rellevància?",
        "Com detectar urgències sense amplificar alarmisme?"
      ],
    },
  ],

  actualitat: [
    {
      date: "2026-05-16",
      title: "La Generalitat destina cinc milions d'euros a formació en IA per a treballadors públics",
      category: "administratiu",
      source: "Regio7",
      urgency: "normal",
      summary: "La notícia apunta a una aposta institucional per capacitació en IA dins l'administració. El punt jurídic rellevant és la governança d'ús: protocols, responsabilitat de decisió humana i traçabilitat de processos assistits.",
      why: "Impacta contractació pública, procediment administratiu i qualitat del servei públic digital.",
      url: "https://www.regio7.cat/arreu-catalunya-espanya-mon/2026/05/16/generalitat-destina-cinc-milions-euros-formacio-intelligencia-artificial-funcionaris-catalunya-salvador-illa-ia-microsoft-130286894.html"
    },
    {
      date: "2026-05-15",
      title: "DOGC publica nous moviments normatius en tramitació digital",
      category: "regulatori",
      source: "DOGC",
      urgency: "normal",
      summary: "La tendència consolida la digitalització procedimental i obliga a revisar terminis, notificació electrònica i prova de recepció. El resum IA prioritza els canvis que poden afectar litigi o compliance a curt termini.",
      why: "Convé anticipar impacte en obligacions formals i en estratègia de resposta processal.",
      url: "https://dogc.gencat.cat/"
    },
    {
      date: "2026-05-14",
      title: "Debat sobre transparència algorítmica en serveis públics i resolucions assistides",
      category: "ia i dret",
      source: "Parlament",
      urgency: "alta",
      summary: "Els actors institucionals reclamen criteris mínims d'explicabilitat en eines de suport a decisió. El resum IA destaca riscos de biaix, opacitat contractual i necessitat de control extern independent.",
      why: "Pot generar noves exigències de supervisió i auditoria en administracions i proveïdors.",
      url: "https://www.parlament.cat/"
    }
  ],

  papers: [
    {
      title: "Línia editorial en preparació",
      authors: "Ius Quanticum",
      venue: "Secció en construcció",
      year: 2026,
      links: ["aviat"],
      cit: "—",
    },
  ],

  workingPapers: [
    {
      title: "Notes de recerca i materials oberts",
      authors: "Ius Quanticum",
      venue: "En desenvolupament progressiu",
      year: 2026,
      links: ["aviat"],
      cit: "—",
    },
  ],

  talks: [
    { when: "2026", what: "Recerca i intervencions encara no publicades", where: "Secció en construcció" },
  ],
};
