// Content for the site — kept as a global window.SITE so other files can reach it.

window.SITE = {
  posts: [
    {
      slug: "grover-discovery",
      date: "2026-04-22",
      readMin: 14,
      title: "Grover's algorithm and the discovery problem",
      dek: "If a quantum search is quadratically faster, what does a defensible e-discovery protocol look like when the other side has one and you don't?",
      tags: ["quantum", "litigation", "evidence"],
      body: "grover-discovery",
    },
    {
      slug: "probabilistic-precedent",
      date: "2026-03-08",
      readMin: 11,
      title: "Probabilistic precedent",
      dek: "When an LLM reads ten thousand decisions and tells you that p(reversal)=0.61, what kind of legal object is that number?",
      tags: ["ai", "jurisprudence"],
    },
    {
      slug: "expert-witness-pqc",
      date: "2026-02-19",
      readMin: 9,
      title: "The expert witness problem in post-quantum cases",
      dek: "Lattice cryptography has no good metaphor, and metaphor is most of what an expert sells to a jury.",
      tags: ["quantum", "evidence", "practice"],
    },
    {
      slug: "drafting-pqc-clauses",
      date: "2026-01-14",
      readMin: 8,
      title: "Drafting around the post-quantum migration",
      dek: "A short field-guide for contract clauses that don't break the moment NIST publishes anything new.",
      tags: ["contracts", "quantum"],
    },
    {
      slug: "hallucinations-evidence",
      date: "2025-12-02",
      readMin: 16,
      title: "AI hallucinations as evidence: a doctrinal sketch",
      dek: "Federal Rule 901 wasn't drafted with a model that confidently confabulates citations in mind. It also doesn't need to be replaced.",
      tags: ["ai", "evidence", "doctrine"],
    },
    {
      slug: "arbitration-quantum-first",
      date: "2025-10-30",
      readMin: 7,
      title: "Why arbitration will meet quantum first",
      dek: "Private dispute resolution has stronger incentives to upgrade its cryptography than any court system — and weaker constraints on doing so.",
      tags: ["arbitration", "quantum"],
    },
    {
      slug: "model-cards-as-pleadings",
      date: "2025-09-11",
      readMin: 6,
      title: "Model cards as pleadings",
      dek: "Notes from a half-hearted proposal that the model card is the new 12(b)(6) attachment.",
      tags: ["ai", "procedure"],
    },
  ],

  projects: [
    {
      slug: "lex-superposition",
      name: "lex-superposition",
      tagline: "Quantum-inspired case retrieval that returns a distribution, not a list.",
      status: "beta",
      year: "2026",
      stack: "Qiskit · Postgres · TypeScript",
      kind: "tool",
      body: "lex-superposition",
    },
    {
      slug: "obiter",
      name: "obiter",
      tagline: "An open marginalia layer for case law. Annotate decisions like a 19th-century reader.",
      status: "live",
      year: "2025",
      stack: "Rust · WASM · CRDTs",
      kind: "tool",
    },
    {
      slug: "qkd-clauses",
      name: "qkd-clauses",
      tagline: "Drafting kit for post-quantum cryptography clauses across NDA, SaaS, and procurement.",
      status: "live",
      year: "2025",
      stack: "Markdown · Pandoc",
      kind: "kit",
    },
    {
      slug: "amicus-fm",
      name: "amicus.fm",
      tagline: "An open archive of amicus briefs in AI and quantum cases — full text, structured.",
      status: "concept",
      year: "2026",
      stack: "Postgres · Meilisearch",
      kind: "archive",
    },
  ],

  papers: [
    {
      title: "Grover-bounded discovery: a framework for proportionality under quantum search asymmetry",
      authors: "Vasconcelos, M., & Halász, M.",
      venue: "Stanford Journal of Law & Technology, 28(2), 211–268",
      year: 2026,
      links: ["pdf", "ssrn", "cite"],
      cit: "n=3",
    },
    {
      title: "Hallucination, authentication, and the residue of Rule 901",
      authors: "Vasconcelos, M.",
      venue: "Yale Journal on Regulation, 43(1), 88–141",
      year: 2025,
      links: ["pdf", "html", "cite"],
      cit: "n=27",
    },
    {
      title: "Cryptographic obsolescence in long-tail contracts",
      authors: "Vasconcelos, M., & Reis, C.",
      venue: "Berkeley Tech. L. J., 39(4), 1102–1149",
      year: 2024,
      links: ["pdf", "cite"],
      cit: "n=42",
    },
    {
      title: "A jurimetric reading of model card disclosures",
      authors: "Vasconcelos, M.",
      venue: "Journal of Empirical Legal Studies, 21(2), 305–337",
      year: 2024,
      links: ["pdf", "ssrn", "code", "cite"],
      cit: "n=61",
    },
    {
      title: "On the impossibility of perfect AI auditing under model drift",
      authors: "Halász, M., & Vasconcelos, M.",
      venue: "Harvard J.L. & Tech., 37(3), 615–662",
      year: 2023,
      links: ["pdf", "cite"],
      cit: "n=108",
    },
  ],

  workingPapers: [
    {
      title: "Post-quantum standing: who can sue when an algorithm is the threat?",
      authors: "Vasconcelos, M. — draft v0.4",
      venue: "Working paper · last revised April 2026",
      year: 2026,
      links: ["pdf draft", "comments"],
      cit: "draft",
    },
    {
      title: "Probabilistic precedent and the burden of disagreement",
      authors: "Vasconcelos, M., & Reis, C. — draft v0.2",
      venue: "Working paper · last revised February 2026",
      year: 2026,
      links: ["pdf draft"],
      cit: "draft",
    },
    {
      title: "The expert witness problem under lattice cryptography",
      authors: "Vasconcelos, M.",
      venue: "Working paper · last revised December 2025",
      year: 2025,
      links: ["pdf draft", "notes"],
      cit: "draft",
    },
  ],

  talks: [
    { when: "Jun 2026", what: "Keynote — Discovery After Grover", where: "Stanford CodeX FutureLaw" },
    { when: "Apr 2026", what: "Panel — AI Evidence in Federal Courts", where: "Berkman Klein Center" },
    { when: "Mar 2026", what: "Workshop — Drafting for the Post-Quantum Migration", where: "ITechLaw, Lisbon" },
    { when: "Nov 2025", what: "Talk — On Probabilistic Precedent", where: "Yale ISP Speaker Series" },
    { when: "Sep 2025", what: "Tutorial — Quantum Search for Lawyers", where: "ABA Techshow" },
    { when: "May 2025", what: "Paper — Cryptographic Obsolescence", where: "We Robot, Seattle" },
  ],
};
